const { withXcodeProject, withDangerousMod, IOSConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Custom Expo config plugin to inject native iOS DeviceMonitor module files
 * into the Xcode project during prebuild (runs on EAS Build's macOS servers).
 */

const SWIFT_FILES = [
  'DeviceMonitorModule.swift',
  'IPhoneModelMapper.swift',
];

const OBJC_FILES = [
  'DeviceMonitorBridge.m',
];

function withDeviceMonitorIOS(config) {
  // Step 1: Copy native files into ios/ directory
  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const iosPath = path.join(projectRoot, 'ios');
      const projectName = config.modRequest.projectName || 'MobileMonitor';
      const targetDir = path.join(iosPath, projectName);
      const sourceDir = path.join(projectRoot, 'ios-native');

      // Ensure target directory exists
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      // Copy all native files
      const allFiles = [...SWIFT_FILES, ...OBJC_FILES];
      for (const file of allFiles) {
        const src = path.join(sourceDir, file);
        const dst = path.join(targetDir, file);
        if (fs.existsSync(src)) {
          fs.copyFileSync(src, dst);
          console.log(`[DeviceMonitor] Copied ${file} to ${targetDir}`);
        } else {
          console.warn(`[DeviceMonitor] Warning: ${src} not found`);
        }
      }

      // Create bridging header if it doesn't exist
      const bridgingHeaderPath = path.join(targetDir, `${projectName}-Bridging-Header.h`);
      if (!fs.existsSync(bridgingHeaderPath)) {
        const bridgingHeaderContent = `//
//  ${projectName}-Bridging-Header.h
//  Auto-generated by DeviceMonitor config plugin
//

#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
`;
        fs.writeFileSync(bridgingHeaderPath, bridgingHeaderContent);
        console.log(`[DeviceMonitor] Created bridging header: ${bridgingHeaderPath}`);
      }

      return config;
    },
  ]);

  // Step 2: Add files to the Xcode project
  config = withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults;
    const projectName = config.modRequest.projectName || 'MobileMonitor';
    const projectRoot = config.modRequest.projectRoot;
    const targetDir = path.join(projectRoot, 'ios', projectName);

    // Find the main group
    const mainGroup = xcodeProject.getFirstProject().firstProject.mainGroup;
    
    // Find or create the project group
    let projectGroup = null;
    const groups = xcodeProject.hash.project.objects['PBXGroup'];
    for (const key in groups) {
      if (typeof groups[key] === 'object' && groups[key].name === projectName) {
        projectGroup = key;
        break;
      }
    }

    // Add Swift files
    for (const file of SWIFT_FILES) {
      const filePath = path.join(targetDir, file);
      if (fs.existsSync(filePath)) {
        xcodeProject.addSourceFile(
          `${projectName}/${file}`,
          { target: xcodeProject.getFirstTarget().uuid },
          projectGroup
        );
        console.log(`[DeviceMonitor] Added ${file} to Xcode project`);
      }
    }

    // Add Objective-C files
    for (const file of OBJC_FILES) {
      const filePath = path.join(targetDir, file);
      if (fs.existsSync(filePath)) {
        xcodeProject.addSourceFile(
          `${projectName}/${file}`,
          { target: xcodeProject.getFirstTarget().uuid },
          projectGroup
        );
        console.log(`[DeviceMonitor] Added ${file} to Xcode project`);
      }
    }

    // Set bridging header in build settings
    const buildConfigs = xcodeProject.hash.project.objects['XCBuildConfiguration'];
    for (const key in buildConfigs) {
      if (typeof buildConfigs[key] === 'object' && buildConfigs[key].buildSettings) {
        const settings = buildConfigs[key].buildSettings;
        if (!settings['SWIFT_OBJC_BRIDGING_HEADER']) {
          settings['SWIFT_OBJC_BRIDGING_HEADER'] = `${projectName}/${projectName}-Bridging-Header.h`;
        }
        // Ensure Swift version is set
        if (!settings['SWIFT_VERSION']) {
          settings['SWIFT_VERSION'] = '5.0';
        }
      }
    }

    return config;
  });

  return config;
}

module.exports = withDeviceMonitorIOS;
